### ISSUE TITLE
footer is fixed - it doesn't leave to see content in the bottom

### ISSUE THREAD

**Issue by dpshelio** [OpenAstronomy/openastronomy.github.io#60]
In some cases, the visitor needs to zoom out so to see the content at the bottom.
![screenshot from 2017-01-29 16-10-46](https://cloud.githubusercontent.com/assets/963242/22405630/93948032-e63d-11e6-8f98-517a7712fa6a.png)

**Comment by eteq** [comment]
OMG.  I've been trying to fix this but it just seems completely impossible... I'm wondering if we should just forego the footer entirely?  Or Move it to be fixed at the actual bottom of the page?

**Comment by eteq** [comment]
(Because right now it makes a lot of the content un-readable on some size screens, especially on the "members" page)

**Comment by wtbarnes** [comment]
solved by #67? Though now it seems like there's an excess of space at the bottom of the page.

**Comment by Cadair** [comment]
I pushed a slightly different fix, can people see if it works now?

**Comment by eteq** [comment]
Still not fixed for me...

**Comment by eteq** [comment]
The root of the problem seems to be that the <div> that has the content is not expanding to the size of the content, so there's no straightforward  way to add padding at the "bottom".

An alternative would to have the footer just be at the bottom, rather than be floating....?

**Comment by Cadair** [comment]
@eteq what browser / pages are still broken? I did a pretty through run though and it looked good to me.

**Comment by wtbarnes** [comment]
Now the footer is overlapping again.

**Comment by eteq** [comment]
Looks like it's only the front page now...?

**Comment by eteq** [comment]
It's good for me now, following  #76 !  I'm going to close this, but if it re-occurs we can re-open it.
